[project]
name = "ai_fish_tank"
version = "0.1.0"
description = "AI Fish Tank"
authors = [
    { name = "Matthew Martin", email = "matthewdeanmartin@gmail.com" },
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.13"
keywords = ["fish-tank", "openai"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "openai>0.28",
    "diskcache",
    "httpx",
    "colorlog>=6.8.0,<7",
    "bug-trail-core",
    "python-dotenv>=1.0.1",
]

[project.urls]
"Bug Tracker" = "https://github.com/matthewdeanmartin/ai_fish_tank/issues"
"Change Log" = "https://github.com/matthewdeanmartin/ai_fish_tank/blob/main/CHANGELOG.md"

[project.scripts]
ai_fish_tank = 'ai_fish_tank.__main__:run'
ais = 'ai_fish_tank.__main__:run'


[dependency-groups]
dev = [
    "mypy>=1.8.0",
    "pylint>=3.0.2",
    "ruff",
    
    "pytest",
    "pytest-cov",
    "pytest-xdist>=3.5.0",
    "pytest-randomly>=3.15.0",
    "pytest-sugar>=0.9.7",
    "pytest-mock",
    "pytest-unused-fixtures",
    "hypothesis[cli]",
    "pytest>=7.4.3",
    "pytest-cov>=4.1.0",
    "pytest-snapshot",
    "pytest-asyncio",
    "pytest-network",

    "time-machine",
    "pytest-mock>=3.14.0",
    "hypothesis>=6.99.13",
    "tox",
    "black>=23.11.0",
    "pre-commit>=3.5.0",
    "interrogate>=1.5.0",
    "pydoctest>=0.1.22", "pdoc3>=0.10.0", "mdformat>=0.7.17",
    "linkcheckmd>=1.4.0",
    "codespell>=2.2.6", "pyenchant>=3.2.2",
    "metametameta>=0.1.0",
    "keepachangelog-manager"
]

[tool.black]
line-length = 120
target-version = ['py39']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''
#
#[tool.poetry.build]
#generate-setup-file = false
#script = "build.py"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "test",
    "tests"
]
junit_family = "xunit1"
norecursedirs = ["vendor", "scripts"]
# don't know how to do this in toml
#addopts = "--strict-markers"
#markers =
#	slow: marks tests as slow (deselect with '-m "not slow"')
#	fast: marks tests as fast (deselect with '-m "not fast"')


[tool.isort]
default_section = "THIRDPARTY"
force_grid_wrap = 0
include_trailing_comma = true
known_first_party = ["dedlin"]
line_length = 120
multi_line_output = 3
use_parentheses = true

[tool.ruff]
line-length = 1000

# Enable Pyflakes `E` and `F` codes by default.
select = ["E", "F",
    "D", # docs
    "UP", # pyupgrade
    "B", # bugbear
]
ignore = [
    "E722",
    # only track structural problems with docstrings, not whitespace, nor missing
    "D200", "D212", "D415", "D411", "D205", "D102", "D103", "D100", "D107", "D101", "D104", "D105",
    "UP007", "UP038", # Not sure if | is well supported in lowever versions of python
]

# Exclude a variety of commonly ignored directories.
exclude = [
    "dead_code",
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "tests_TODO",
    "ai_fish_tank_on_hold"
]
per-file-ignores = { }

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.13.
target-version = "py313"


[tool.ruff.lint.pydocstyle]
convention = "google"


[tool.bug_trail]
app_name = "ai_fish_tank"
app_author = "matthewdeanmartin"
source_folder = "ai_fish_tank"
#ctags_file = "fish_tank.tags"

[tool.bug-trail]
app_name = "ai_fish_tank"
app_author = "matthewdeanmartin"
report_folder = "logs"
database_path = "bug_trail.db"
[tool.uv]
universal = true
